[production]
192.168.100.19 #samiservices.malauzai.com
production2.malauzai.com
production1.malauzai.com
production3.malauzai.com
staging.malauzai.com
cbproduction3.malauzai.com
cbproduction4.malauzai.com
cbproduction1.malauzai.com
cbproduction2.malauzai.com
ofx1.malauzai.com
ofx2.malauzai.com
sftp.malauzai.com
nfs.malauzai.com
console.malauzai.com
redis.malauzai.com
alertengine.malauzai.com
cbredis.malauzai.com

[host_files]
production1.malauzai.com
production2.malauzai.com
production3.malauzai.com
production4.malauzai.com
preproduction.malauzai.com
rsdevelopment.malauzai.com
demo.malauzai.com
samiservices.malauzai.com

[hq]
radius
