- hosts:  host_files   
  become: true
  tasks:
      - lineinfile:
          dest: /etc/hosts
          state: present
          insertafter: EOF
          line: '10.52.1.166	appexchange.ky06.membersheritage.org' #this will need to contain the host you want to add
