---
 - hosts: switch01
   gather_facts: true
   connection: local
#   vars:
#     cli: 
#       host: "{{ inventory_hostname }}"
#       username: cisco
#       password: 13k4FFnmTIln
  
   tasks:
    - name: show run
      ios_command:
       commands: 
         - terminal datadump
         - show run
      register: config

    - name: save output
      copy:
      content: "{{ config.stdout[0] }}"
      dest: "/etc/ansible/show_run_{{ inventory_hostname }}.txt"
 
